### ISSUE TITLE
Example Sketch Request - 'Live' Data Uplink

### ISSUE THREAD

**Issue by K4KDR** [sparkfunX/Satellite_Transceiver_Breakout__Swarm_M138#1]
The M138 is working spectacularly well - way beyond my expectations.  Thanks to all involved.

The Arduino examples are very helpful.  There are examples on how to transmit static text or hex strings as well as examples on how to perform essentially 'Serial Console' type interactions with the M138.

Would it be possible to see an example that illustrates how the M138 will probably be most commonly used:  to **upload sensor data on a periodic (i.e., once per hour) basis?**   I am referring to analog sensors (air temperature, for example) that would be connected to one of the Arduino's input pins and on a periodic basis, the most current 'live' value uploaded via satellite.  

In fact, I have already heard from one person tasked with with monitoring environmental data in an EXTREMELY remote location and naturally he is very interested in your product & the SWARM service.  However, while I already use Arduino devices to uplink that kind of data via other LoRa hats as well as via the local IP network, I'm not clear how to submit a 'live' value on a scheduled basis for upload via the M138. (I realize messages have to be queued, so the telemetry won't be EXACTLY live... just looking to acquire the current value once per hour for submission to the uplink queue)

Thanks in advance for any guidance on this!

-Scott,  K4KDR

**Comment by PaulZC** [comment]
Hi Scott,

Assuming you want to send your sensor data in text format, the critical lines of code are these:

https://github.com/sparkfun/SparkFun_Swarm_Satellite_Arduino_Library/blob/b2a912294154c3e5fa0529661527b384e36c3efe/examples/Example14_transmitText/Example14_transmitText.ino#L75-L78

```mySwarm.transmitText``` is the function which adds the message (contained in the ```myMessage``` char array) to the modem's transmit queue.

If you wanted to, you could include the local time or modem time in the message itself (together with your sensor data). That way, you would know the time the readings were taken, rather than the time the message was transmitted / delivered etc..

There are many ways of 'triggering' the transmit once per hour. Using Arduino ```millis()``` is the simplest. The code would look something like:

```
static unsigned long lastTransmit;

if (millis() > (lastTransmit + 3600000)) // Transmit once per hour
{
  lastTransmit = millis(); // Update lastTransmit
  uint64_t id;
  char myMessage[192];
  // Add your own code here to put your sensor readings into myMessage in text format
  // Add a 'null' (zero) to mark the end of the data
  Swarm_M138_Error_e err = mySwarm.transmitText((const char *)myMessage, &id);
  // Do something with id here - if you want to
}
```

Is that the kind of thing you are looking for?

Best wishes,
Paul

**Comment by K4KDR** [comment]
Thank you for the reply!

My concern from the examples was that the setting of the upload string was static & then the code just listened for opportunities to transmit when a satellite was heard:

```
void loop()
{
  mySwarm.checkUnsolicitedMsg();
}
```

... so, the analog value could get old and was never updated.   It looks like your new code:

```
if (millis() > (lastTransmit + 3600000)) // Transmit once per hour
{
  lastTransmit = millis(); // Update lastTransmit
  uint64_t id;
  char myMessage[192];
  // Add your own code here to put your sensor readings into myMessage in text format
  // Add a 'null' (zero) to mark the end of the data
  Swarm_M138_Error_e err = mySwarm.transmitText((const char *)myMessage, &id);
  // Do something with id here - if you want to
}
```

... will take care of that nicely.  Can't wait to test it out.  Thanks very much!!

**Comment by PaulZC** [comment]
Hi Scott,

The examples are a bit 'cluttered'. My bad...

Let me try and simplify the transmit message process:

As we discussed above, you queue a message for transmission using ```mySwarm.transmitText``` (or ```mySwarm.transmitBinary``` ). Once the message is in the transmit queue, the modem will transmit it on the next satellite pass - without needing any further intervention. All you need to do is keep the modem powered on and awake.

There are two ways to tell if your message has been transmitted. You can:
* Check how many messages are in the transmit queue with ```getUnsentMessageCount```
  * When this returns to zero, you know all messages have been sent
* Or wait for the unsolicited ```$TD SENT``` to arrive
  * A ```$TD SENT``` message is generated each time a message is sent
  * It contains the ```msg_ID``` of the message that has just been sent plus other information about the signal strength etc.

You can manually poll the unsent message count as often as you want to.

If you want to make use of the ```$TD SENT``` message, then you need to:
* Set up a callback for it - with ```setTransmitDataCallback```
* Call ```checkUnsolicitedMsg``` often

The callback is called as soon as ```checkUnsolicitedMsg``` 'intercepts' the ```$TD SENT```.


If you unpick the examples a bit, you will find that they show: how to do things manually; and how to use callbacks to help.

E.g. for the GPS Geospatial Information:
* You can request (poll) the geospatial information manually using [getGeospatialInfo](https://github.com/sparkfun/SparkFun_Swarm_Satellite_Arduino_Library/blob/b2a912294154c3e5fa0529661527b384e36c3efe/examples/Example5_GeospatialInformation/Example5_GeospatialInformation.ino#L81)
* And/or you can:
  * Set up a [callback for the $GN message](https://github.com/sparkfun/SparkFun_Swarm_Satellite_Arduino_Library/blob/b2a912294154c3e5fa0529661527b384e36c3efe/examples/Example5_GeospatialInformation/Example5_GeospatialInformation.ino#L97)
  * Enable [unsolicited $GN messages](https://github.com/sparkfun/SparkFun_Swarm_Satellite_Arduino_Library/blob/b2a912294154c3e5fa0529661527b384e36c3efe/examples/Example5_GeospatialInformation/Example5_GeospatialInformation.ino#L101) at your desired rate/interval
  * Call [checkUnsolicitedMsg](https://github.com/sparkfun/SparkFun_Swarm_Satellite_Arduino_Library/blob/b2a912294154c3e5fa0529661527b384e36c3efe/examples/Example5_GeospatialInformation/Example5_GeospatialInformation.ino#L138) often
  * The [callback](https://github.com/sparkfun/SparkFun_Swarm_Satellite_Arduino_Library/blob/b2a912294154c3e5fa0529661527b384e36c3efe/examples/Example5_GeospatialInformation/Example5_GeospatialInformation.ino#L43-L55) is called when a $GN message arrives

One final piece of advice: once an unsolicited message is enabled, you have to [un-enable it](https://github.com/sparkfun/SparkFun_Swarm_Satellite_Arduino_Library/blob/b2a912294154c3e5fa0529661527b384e36c3efe/examples/Example18_DisableUnsolicitedMessages/Example18_DisableUnsolicitedMessages.ino#L53-L59) to stop it being produced. The modem remembers which unsolicited messages are enabled, even when power-cycled. The only ones you cannot disable are ```$TD SENT``` and ```$M138```.

Have fun!
Paul

**Comment by K4KDR** [comment]
Thanks again for all the help - much appreciated!!

An update:  https://twitter.com/scott23192/status/1533526372768960512

**Comment by PaulZC** [comment]
Linking this to issue 21 in the Library repo. That's also a request for a data uplink example:

https://github.com/sparkfun/SparkFun_Swarm_Satellite_Arduino_Library/issues/21
