### ISSUE TITLE
5v Logic Tolerance?

### ISSUE THREAD

**Issue by K4KDR** [sparkfunX/Satellite_Transceiver_Breakout__Swarm_M138#2]
Since I have to think that I won't be the last person to make this mistake, a question please...

Wanting to test 'Sleep' Mode with the Arduino device connected to my M138, I found that the Arduino Due that I had was not supported by the same **avr/sleep.h** library that is most commonly used.  So, I purchased a couple of MEGA boards to use with the M138 to allow me to experiment with Sleep mode.

However, for several minutes after connecting one of the hardware serial UART connections from the MEGA to the M138, I forgot about the M138's requirement for 3.3v logic levels.  During that time, a message was queued and things appeared to work normally.  However, I immediately disconnected power from both devices and am in the process of wiring up a logic level shifter board between the MEGA & the M138.

Does the M138 have (I hope) "some" tolerance to the presence of a 5v logic level on the serial RX/TX pins?    Fingers crossed that all is well when I re-wire with the 5v/3.3v level shifter in place.

Thanks!

-Scott,  K4KDR

**Comment by PaulZC** [comment]
Hi Scott,

This is (probably) a case of "you've got away with it". It is normal for microcontrollers to have protection diodes on their IO pins. If the pin voltage is taken above VCC (3.3V) the diode starts dumping current from the pin to the VCC rail. They're there to cope with brief over-voltage (ESD-like) events. Also the IO (UART) pins on the MEGA will only be able to deliver limited current. Put those two things together and your're _**probably**_ OK.

Proper level-shifters are the best way to go.

I don't know what the quiescent current draw of the MEGA board will be with the processor in sleep. It is probably still quite high. There's a bunch of stuff on there that will keep drawing current even if the processor isn't. If you really want to get the sleep current right down, you need a board that has been designed for it. Our [OpenLog Artemis](https://www.sparkfun.com/products/19426) was designed that way. Take a look at Unexpected Maker's boards too - he's doing great things with the sleep current.

Best wishes,
Paul

**Comment by PaulZC** [comment]
Closing...

**Comment by K4KDR** [comment]
Thanks so much for the VERY informative reply!   I will certainly check out those other boards. 

Yes, now that everything is powered back up with level shifters on all connections, everything seems fine.  Serial Monitor feedback is all correct & messages are uploading via satellite. 

Thanks again!
