### ISSUE TITLE
BOM

### ISSUE THREAD

**Issue by tremmert81** [sparkfunX/Satellite_Transceiver_Breakout__Swarm_M138#3]
Is it possible for you to upload the BOM?  I am not finding anything in this repository..

**Comment by PaulZC** [comment]
Hi @tremmert81 ,

If you download the free version of Eagle, you can open the hardware files and create the BOM for yourself. But - to save you some time - I've added a couple of different versions to the [Hardware folder](https://github.com/sparkfunX/Satellite_Transceiver_Breakout__Swarm_M138/tree/main/Hardware).

Best wishes,
Paul
